//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace agdregbak
{
    using System;
    using System.Collections.Generic;
    
    public partial class register
    {
        public int Id { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public string mobile { get; set; }
        public string email { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string postal { get; set; }
        public string address { get; set; }
        public string photo { get; set; }
        public string nrcfront { get; set; }
        public string nrcback { get; set; }
        public Nullable<int> service_Id { get; set; }
        public string status { get; set; }
        public string refno { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<System.DateTime> review_date { get; set; }
        public string review_message { get; set; }
        public string gender { get; set; }
        public string fathername { get; set; }
        public string nrcno { get; set; }
        public string signature { get; set; }
    }
}
