//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace agdregbak
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AGDRegEntities : DbContext
    {
        public AGDRegEntities()
            : base("name=AGDRegEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<request> requests { get; set; }
        public virtual DbSet<service> services { get; set; }
        public virtual DbSet<servicetype> servicetypes { get; set; }
        public virtual DbSet<register> registers { get; set; }
    }
}
